### ISSUE TITLE
Router class not defined on index.php

### ISSUE THREAD

**Issue by reflexLabs** [crjoseabraham/php-basic-mvc#1]
I just clone this project (thank you btw (: )
and I get this error:
```
Fatal error: Uncaught Error: Class "App\Router" not found in D:\xampp\htdocs\public\index.php:5 Stack trace: #0 {main} thrown in D:\xampp\htdocs\public\index.php on line 5
```

**Comment by crjoseabraham** [comment]
Hi, thank you for trying this project. I will gladly help you solve your problem but I'm afraid I can't reproduce the error you mention. I did this to get it to work:

1. After  cloning or downloading the repository. Import the .sql file inside `data/todo_db.sql` to phpmyadmin or create the database manually naming it "todo_db" (you will also need a table named "tasks" with the fields id [int], description [string], completed [bool])
2. Run `composer install` from the project folder (try running it twice if you get ambiguous message)

Some things I realized just now:

- In `config/constants.php` you have to change the value for `URLROOT` to `'http://localhost/php-mvc'` instead of `'http://localhost/php-basic-mvc'` 
- Also, in `public/.htaccess` change this line `RewriteBase /php-basic-mvc/public` to `RewriteBase /php-mvc/public`
(I will update this part of the code soon but for now, please do it yourself)

After that, go to `localhost/php-mvc`. Try that and let me know if you still get the error

**Comment by reflexLabs** [comment]
I tried an other project and figured out what was the issue, thank you very much for the response tho!
